# TCL File Generated by Component Editor 11.0
# Fri Dec 09 16:33:01 MST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | calibrate_avalon "calibration_block" v1.0
# | null 2011.12.09.16:33:01
# | 
# | 
# | C:/NRCRee475/Final Project/DE2_System/calibrate_avalon.vhd
# | 
# |    ./calibrate.vhd syn, sim
# |    ./calibrate_avalon.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module calibrate_avalon
# | 
set_module_property NAME calibrate_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSP
set_module_property DISPLAY_NAME calibration_block
set_module_property TOP_LEVEL_HDL_FILE calibrate_avalon.vhd
set_module_property TOP_LEVEL_HDL_MODULE calibrate_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file calibrate.vhd {SYNTHESIS SIMULATION}
add_file calibrate_avalon.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data
# | 
add_interface data conduit end

set_interface_property data ENABLED true

add_interface_port data data export Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point x_coord
# | 
add_interface x_coord conduit end

set_interface_property x_coord ENABLED true

add_interface_port x_coord x_coord export Input 9
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point y_coord
# | 
add_interface y_coord conduit end

set_interface_property y_coord ENABLED true

add_interface_port y_coord y_coord export Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_cal
# | 
add_interface data_cal conduit end

set_interface_property data_cal ENABLED true

add_interface_port data_cal data_cal export Output 16
# | 
# +-----------------------------------
